### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by cheberling** [genomicsITER/NanoCLUST#2]
I have tried installing nextflow through both methods cited on their page: using curl, and using bioconda.  I have then tried to test the nextflow pipeline for Nanoclust using 3 different conda environments for 3 different python versions.  For python versions 3.4 or 3.7 the environment fails to resolve the kmer_freqs package.  For python version 2.7, the pipeline gets further, but still fails to resolve the environment for the read_correction module.

For both I used the following command:

`nextflow run main.nf -profile test,conda`

I am pasting links for my error logs here:
<https://vedantabio.box.com/s/ocuwb22128serr59tob3r3se7bzw8aez>
<https://vedantabio.box.com/s/ccmpuqez10vqd3gmpn6aramx760dwpog>

**Comment by genomicsITER** [comment]
Thank you for contacting us and giving detailed information.

We've updated the pipeline repository.  We have defined the exact versions to packages in the environment.yml files used for the conda envs. This should fix the errors that arise in some machines when trying to build envorinments like read_clustering and read_correction.

Also the docker profile can be used (-profile test,docker) instead of conda. Docker images with working environments are pulled automatically from Dockerhub.

Please feel free to contact again if problems persist with conda and docker profiles

**Comment by cheberling** [comment]
Still having issues with both the conda and docker methods of initializing workflow.

See following error files:
<https://vedantabio.box.com/s/seavazi4yhxjj2ldz39w7a1rbotrilj7>
<https://vedantabio.box.com/s/rup8zstxulwpo2wmzzyulaw6an0rbdkd>
<https://vedantabio.box.com/s/3gtt3ggwg8zefoajqkwtxq2892mhd4fr>

**Comment by genomicsITER** [comment]
Hi, thank you for your time. I've checked the error files:

It's seems that you continue having the same dependency problem with that conda env. I recommend deleting your work directory where conda envs are stored to build them all again. 

When running with the docker profile, the pipeline doesn't even start docker on your machine. I would check if your docker installation is working properly (user or sudo mode) and if any docker image was pulled ($docker images) when you get the same error again.

**Comment by cheberling** [comment]
I have tried removing the work directory and starting over, I am still getting errors with the read correction module, which seems to be a problem with the canu installation.  There is a perl mismatch with ListUtil.c:

```
Error executing process > 'read_correction (4)'

Caused by:
  Process `read_correction (4)` terminated with an error exit status (1)

Command executed:

  head -n$(( 20*4 )) 3.fastq > subset.fastq
  canu -correct -p corrected_reads -nanopore-raw subset.fastq genomeSize=1.5k stopOnLowCoverage=1 minInputCoverage=2
  gunzip corrected_reads.correctedReads.fasta.gz
  READ_COUNT=$(( $(awk '{print $1/2}' <(wc -l corrected_reads.correctedReads.fasta)) ))
  cat 3.log > 3_racon.log
  echo -n ";20;$READ_COUNT;" >> 3_racon.log && cp 3_racon.log 3_racon_.log

Command exit status:
  1

Command output:
  (empty)

Command error:
  ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)

Work dir:
  /vedanta/sw/packages/NanoCLUST/work/9b/c1a124ef8d236dfe65d4004735107e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I fixed my docker installation, but it's having a permissions issue with connecting to the docker daemon:

```
Error executing process > 'QC (1)'

Caused by:
  Process `QC (1)` terminated with an error exit status (126)

Command executed:

  barcode=mock4_run3bc08_5000
  fastp -i mock4_run3bc08_5000.fastq -q 8 -l 1400 --length_limit 1700 -o $barcode\_qced_reads.fastq
  #perl prinseq-lite.pl -fastq mock4_run3bc08_5000.fastq -out_good qced_reads -min_len 1400 -max_len 1700 -log qc_log -min_qual_mean 8
  head -n$(( 100000*4 )) $barcode\_qced_reads.fastq > $barcode\_qced_reads_set.fastq

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=nxf-LjUsr2Arnhn3TCNUcg7vABXy: dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /vedanta/sw/packages/NanoCLUST/work/cb/973591a5bc52264eed78103d3721d8

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by genomicsITER** [comment]
The error you are getting with the docker profile could be solved running the pipeline as sudo but I'd rather recommend to follow read instructions to run docker as your regular user. https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket.

For the conda profile, I think that you may have an installation of perl on your machine or conda binaries that it is conflicting with canu's dependencies. I recommend to make the docker profile work, that ensures a more stable execution environment, but for solving conda issues you can try:
-clean the work directory again
-update your packages with "apt-get update"
-clean completely the conda caches "conda clean -a"
-make sure you have the latest version of the repository

**Comment by cheberling** [comment]
I fixed the permission issues with docker based on the link you sent, but I still seem to be having an issue with the read clustering module.  Truncated error below, and full error log linked below.

```
Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File ".command.sh", line 4, in <module>
      import umap
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/umap/__init__.py", line 1, in <module>
      from .umap_ import UMAP
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/umap/umap_.py", line 53, in <module>
      from umap.layouts import (
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/umap/layouts.py", line 39, in <module>
      def rdist(x, y):
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
      disp.enable_caching()
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
      self._cache = FunctionCache(self.py_func)
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
      self._impl = self._impl_class(py_func)
    File "/opt/conda/envs/read_clustering/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
      raise RuntimeError("cannot cache function %r: no locator available "
  RuntimeError: cannot cache function 'rdist': no locator available for file '/opt/conda/envs/read_clustering/lib/python3.8/site-packages/umap/layouts.py'
```

https://vedantabio.box.com/s/tcr8jey65210d2qiax710du3z5po0gv2

**Comment by genomicsITER** [comment]
Thank you for the information. I'm going to inspect your error better, but would like to know if even executing the pipeline with sudo and the docker profile results in the same error.

**Comment by cheberling** [comment]
I managed to get the initialization workflow to work successfully by using sudo with docker, but only on the header node of our linux cluster.  Our header node only has about 15GB of RAM, so it would be ideal if we could run the workflow on one of our compute nodes (about how much RAM should the standard workflow take?).  When I run the same workflow on one of our compute nodes I get the following error:

`.nextflow/history.lock (Permission denied)` (even with sudo)

When I try without sudo, I get the same error as above with the read clustering module.

**Comment by genomicsITER** [comment]
That error arises from a previous execution with sudo. Just delete the work and .nextflow dir, which contains a cache and that history.lock. Those dirs were created with root permissions.

After that modification, do you get the same error with read_correction in the compute node?

**Comment by cheberling** [comment]
After making those changes, I still get the same errors with the read_clustering module when running without sudo, and with sudo I get the following error:

`.nextflow/history.lock (No such file or directory)`

**Comment by genomicsITER** [comment]
Do you get the "_.nextflow/history.lock (No such file or directory)_" executing the pipeline without -resume and a clean work directory?

**Comment by cheberling** [comment]
Yes.

**Comment by genomicsITER** [comment]
Hi

The error with history.lock is from nextflow and seems to be a  strange condition that some files from previous executions are causing. I would clone again the pipeline repo to ensure a clean environment.

I'm trying to emulate the error with libUtils.c. We have used a clean Ubuntu18 VM and also the Bash for Windows to test that the pipeline works with the minimum dependencies installed at its latest version. It is working also on mac os. I wonder if you are using a VM or system that comes with a predefined configuration or packages for certain tasks. Could you tell the OS and version and also versions of Docker ($docker version) and perl (perl -v) if installed?

**Comment by cheberling** [comment]
Ubuntu 16.04.5
Docker 18.09.7
Perl v5.22.1

I'll try a clean install again and report back.

**Comment by cheberling** [comment]
The clean install didn't help (in every attempt I installed nextflow and cloned this git repository fresh).  The problem seems to be with using sudo and how nextflow was installed.  Conda cannot be used with sudo, and so the nextflow installation cannot be used with sudo if it was installed via bioconda.  In order to use sudo, nextflow must be installed using the java executable with cURL.  

Using this method, as I said, the docker installation with sudo works on our header node, but not any of the slave nodes, because it looks for the .nextflow/history.lock and can't find it.

**Comment by genomicsITER** [comment]
If you have have a queue system, you could try executing the nextflow in queue mode. We have not tested this or any nextflow pipelines this way but you can edit the nextflow.config file in the nanoclust root directory to add your configuration to PBS/Torque scheduler. 

https://www.nextflow.io/docs/latest/executor.html#pbs-torque

Thank you for your time

**Comment by cheberling** [comment]
When running without sudo, I have always had write permissions for the nextflow binary.

I cannot run my queue system while using sudo, so until I manage to run the workflow without sudo, that will not work.

For my one environment that worked on the test data, I tried to run on some of my data.  It looked as though the process aborted when attempting multiqc.  For the test data, the pipeline had a warning about not being able to integrate the multiqc report.  I don't care about performing multiqc on the data.  Is there an option in the workflow to skip multiqc?  In the short-term, if I can get the workflow to work with limited computing resources then I may be able to make some progress.

**Comment by genomicsITER** [comment]
Hi,

Definetely the error doesn't relate to this multiqc warning you are getting. The email parameter is from the nf-core template and it is disabled in this pipeline, we will remove these warnings from the code.

We have not experimented with multiqc errors with conda or docker profiles. I assume that FastQC reports that you get seem as expected. Could you provide a log or the exit status for the error?

Also, with the last message I meant that executing the pipeline with the pbs/torque conf shouldn't need super user permissions.

**Comment by cheberling** [comment]
I'm not sure if the log files will help that much, it just said that the pipeline aborted on the multiqc step.  See below:

<https://vedantabio.box.com/s/zn84f8th0yohh46maoah1ln5npu2whl2>
<https://vedantabio.box.com/s/rtaracqhw3vkl55ls12zp0da73dhwil6>

Executing the pipeline with pbs/torque _shouldn't_ need super user permissions, but as we've seen I have only been able to get the pipeline to work on the provided test set while using super user permissions.  We need to figure out how I can get the pipeline to work without sudo first, and then it should be relatively straightforward to get it to run with pbs/torque.

So you are adding no multiqc by default in the next version of the software?  Is that ready now, or do you need to push to the git repository still?

**Comment by genomicsITER** [comment]
I’ve pushed a commit and now multiqc is executed only if —multiqc is included in the command.

**Comment by cheberling** [comment]
When running on my data, the pipeline fails at the same step, even though multiqc is no longer run.  The pipeline doesn't say why it was aborted, it has an error message of 'none'.

**Comment by genomicsITER** [comment]
Does the nextflow.log file say anything? Seems that execution was cut maybe to a java issue but I dont know exactly.

**Comment by cheberling** [comment]
There are some unreadable characters in the log, but I think this is the log you are referring to?  I found it in .nextflow/cache/run_id/db/*.log:

<https://vedantabio.box.com/s/yi9faw8wizxrhnzx8y1w2acetyx2ou6v>

**Comment by genomicsITER** [comment]
You should find a hidden file called .nextflow.log in NanoCLUST base dir or your launch dir that the log of your last execution.

**Comment by genomicsITER** [comment]
Thank you. It definetely is a heap memory error due to a limit in your java configuration. You can modify this and see if you don't get that error.

You could use the command:
`java -Xmx2048m`

for setting the heap max size to 2GB, 4096 for 4GB.

**Comment by cheberling** [comment]
When I used that command by itself on console, I just got usage information.  Where should I use that command?

I think my java version should be up-to-date enough to use nextflow, as it only needs version 8+.

```
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
```

**Comment by genomicsITER** [comment]
I've changed the kmer_freqs process to avoid heap errors. They are in the last commit. I keep on inspecting the problem but tell me if it keeps happening.

**Comment by cheberling** [comment]
Same issue.  See here: <https://vedantabio.box.com/s/1fwvcf626w3q8f92pp61rin9gvlg1rfi>.  As I suspected, it looks like there's not enough memory on our header node.  In order for me to use the pipeline I need to either be able to run it successfully without sudo, or on one of my compute nodes rather than header.

Is there a way we could test individual modules of the pipeline without using nextflow in order to help us troubleshoot?  We could communicate over email to make things easier.

**Comment by genomicsITER** [comment]
Yes, it would be possible to test the modules themselves, we can dicuss that by mail and close the issue.

alu0100774429 (at) ull.edu.es

**Comment by cheberling** [comment]
Just sent you an email, from cheberling (at) vedantabio.com
